[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
name = "test-framework"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
arrow = { workspace = true, features = ["prettyprint", "chrono-tz"] }
async-trait.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["derive"] }
dashmap = "6.1.0"
flight_client = { path = "../flight_client" }
futures.workspace = true
indicatif = "0.18.0"
insta.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
otel-arrow = { path = "../otel-arrow" }
regex.workspace = true
reqwest.workspace = true
rustls.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
yaml = { path = "../yaml" }
spicepod = { path = "../spicepod" }
sysinfo.workspace = true
telemetry = { path = "../telemetry" }
tempfile.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tonic.workspace = true
uuid = { workspace = true, features = ["v4"] }
sqlparser = { version = "0.61", features = ["visitor"] }

[target.'cfg(not(windows))'.dependencies]
nix = { workspace = true }

[dev-dependencies]
rstest = "0.26.1"

