[workspace]
members = ["data-generation"]
resolver = "2"

[workspace.package]
edition = "2024"
homepage = "https://spicebench.com"
license = "Apache-2.0"
repository = "https://github.com/spiceai/spicebench"
rust-version = "1.91"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
arrow = "57.2.0"
arrow-array = "57.2.0"
arrow-schema = "57.2.0"
async-trait = "0.1"
bytes = "1"
clap = { version = "4", features = ["derive"] }
duckdb = { version = "1.4.4", features = ["bundled", "vtab", "vtab-arrow"] }
object_store = { version = "0.12.4", features = ["aws"] }
parquet = "57.2.0"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4"] }

[patch.crates-io]
duckdb = { git = "https://github.com/spiceai/duckdb-rs.git", rev = "f4096c7592ed46b9e68755a49252d69783dece96" } # spiceai-1.4.4

arrow = { git = "https://github.com/spiceai/arrow-rs.git", rev = "ca671dd37d73b730938f77f7a7ad76545280a4a8" }        # spiceai-57.2
parquet = { git = "https://github.com/spiceai/arrow-rs.git", rev = "ca671dd37d73b730938f77f7a7ad76545280a4a8" }      # spiceai-57.2