[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
name = "databricks-system-adapter"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
system-adapter-protocol = { path = "../system-adapter-protocol", features = ["server"] }
tokio.workspace = true
uuid.workspace = true