[package]
name = "checkpointer"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
adbc_client = { path = "../adbc_client" }
anyhow.workspace = true
arrow.workspace = true
async-trait.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["derive"] }
data-generation = { path = "../data-generation" }
etl = { path = "../etl" }
serde_json.workspace = true
system-adapter-protocol = { path = "../system-adapter-protocol" }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }