[package]
name = "checkpointer"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
arrow.workspace = true
clap = { workspace = true, features = ["derive"] }
data-generation = { path = "../data-generation" }
etl = { path = "../etl" }
test-framework = { path = "../test-framework" }
object_store = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
parquet.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[features]
default = []
duckdb = ["etl/duckdb"]