[package]
name = "etl"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "etl"
path = "src/lib.rs"

[[bin]]
name = "etl"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
arrow.workspace = true
clap = { workspace = true, features = ["derive"] }
data-generation = { path = "../data-generation" }
system-adapter-protocol = { path = "../system-adapter-protocol" }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid = { workspace = true, features = ["v4"] }
