[package]
name = "etl"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "etl"
path = "src/lib.rs"

[[bin]]
name = "etl"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
arrow.workspace = true
async-trait.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["derive"] }
data-generation = { path = "../data-generation" }
duckdb = { workspace = true, features = ["bundled", "vtab", "vtab-arrow", "appender-arrow"] }
indexmap = { workspace = true }
object_store = { workspace = true }
serde_json.workspace = true
parquet.workspace = true
system-adapter-protocol = { path = "../system-adapter-protocol" }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[features]
default = []
duckdb = []