[package]
name = "etl"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "etl"
path = "src/lib.rs"

[dependencies]
adbc_client = { path = "../adbc_client" }
anyhow.workspace = true
arrow.workspace = true
arrow-cast = "57"
async-trait.workspace = true
chrono.workspace = true
data-generation = { path = "../data-generation" }
aws-config = { workspace = true, optional = true }
aws-sdk-dynamodb = { workspace = true, optional = true }
duckdb = { workspace = true, optional = true, features = ["bundled", "vtab", "vtab-arrow", "appender-arrow"] }
mongodb = { workspace = true, optional = true }
indexmap = { workspace = true }
object_store = { workspace = true }
serde_json.workspace = true
parquet.workspace = true
system-adapter-protocol = { path = "../system-adapter-protocol" }
tempfile.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true

[features]
default = []
dynamodb = ["dep:aws-config", "dep:aws-sdk-dynamodb"]
duckdb = ["dep:duckdb"]
mongodb = ["dep:mongodb"]