name: Cache spicebench

on:
  push:
    branches:
      - trunk

jobs:
  build-and-cache:
    name: Build and cache spicebench
    runs-on: spiceai-macos
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/build-spicebench
        with:
          lookup-only: 'true'
