name: Scheduled Benchmark Runs
run-name: Scheduled - ${{ github.event_name }}

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: {}  # allow manual trigger for testing

jobs:
  spice-cloud-events:
    name: spice_cloud SF1 events
    uses: ./.github/workflows/run_spicebench_debug_spice_cloud.yml
    with:
      environment: prod
      system_under_test: spice_cloud
      etl_type: events
      scale_factor: '10'
      spidapter_version: latest
      custom_image_tag: latest
      use_private_cluster: true
      app_memory_limit: '16Gi'
      executor_memory_limit: '16Gi'
    secrets: inherit

  spice-cloud-changes:
    name: spice_cloud SF1 changes
    needs: spice-cloud-events
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/run_spicebench_debug_spice_cloud.yml
    with:
      environment: prod
      system_under_test: spice_cloud
      etl_type: changes
      scale_factor: '10'
      spidapter_version: latest
      custom_image_tag: latest
      use_private_cluster: true
      app_memory_limit: '16Gi'
      executor_memory_limit: '16Gi'
    secrets: inherit

  mongodb-events:
    name: mongodb SF1 events
    needs: spice-cloud-changes
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/run_spicebench_debug_streaming.yml
    with:
      environment: production
      system_under_test: mongodb-streams
      acceleration: cayenne
      etl_type: events
      scale_factor: '10'
      spidapter_image_tag: latest
      use_private_cluster: true
      app_memory_limit: '64Gi'
      checkpoint_validation_timeout: '3600'
    secrets: inherit

  mongodb-changes:
    name: mongodb SF1 changes
    needs: mongodb-events
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/run_spicebench_debug_streaming.yml
    with:
      environment: production
      system_under_test: mongodb-streams
      acceleration: cayenne
      etl_type: changes
      scale_factor: '10'
      spidapter_image_tag: latest
      use_private_cluster: true
      app_memory_limit: '64Gi'
      checkpoint_validation_timeout: '3600'
    secrets: inherit
