name: Run spicebench

on:
  workflow_dispatch:

jobs:
  run-spicebench:
    name: Run spicebench
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH
          if [ -d $HOME/.cargo ]; then
            source $HOME/.cargo/env || true
          fi
          if ! command -v rustup &> /dev/null ; then
            curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
            source $HOME/.cargo/env || true
          fi
          rustup toolchain install 1.91
          rustup default 1.91

      - name: Run spicebench
        run: |
          cargo run -p spicebench -- \
            --system-adapter-http-url http://localhost:8080/rpc \
            --system-adapter-execution-mode direct-query \
            --query-set tpch
