name: Run spicebench

on:
  workflow_dispatch:

jobs:
  run-spicebench:
    name: Run spicebench
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/management-login
        with:
          client-id: ${{ secrets.SPICE_MANAGEMENT_CLIENT_ID }}
          client-secret: ${{ secrets.SPICE_MANAGEMENT_CLIENT_SECRET }}

      - run: echo "$SPICE_MANAGEMENT_TOKEN"
      - run: exit 1

      - name: Install Rust
        run: |
          echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH
          if [ -d $HOME/.cargo ]; then
            source $HOME/.cargo/env || true
          fi
          if ! command -v rustup &> /dev/null ; then
            curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
            source $HOME/.cargo/env || true
          fi
          rustup toolchain install 1.91
          rustup default 1.91

      - name: Run spicebench
        run: |
          cargo run -p spicebench -- run \
            --ready-wait 180 \
            --concurrency 2 \
            --query-set tpch
